<<<<<<< HEAD
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
=======
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
>>>>>>> 42e4edbc0649148dfd6494314e9ccbf8f0e88047
